### ISSUE TITLE
inputs.path is not supported

### ISSUE THREAD

**Issue by DennisDenuto** [ryanmoran/piper#4]
In Concourse, inputs allows specifying a path (which the input rootfs is mounted on).

i.e.

```
inputs:
- name: cf-acceptance-tests
  path: gopath/src/github.com/cloudfoundry/cf-acceptance-tests
```

however when running piper the container mounts cf-acceptances-tests to `/tmp/build/cf-acceptance-tests` instead of `/tmp/build/gopath/src/github.com/cloudfoundry/cf-acceptance-tests`. This means we've been unable to use `piper` to iterate on concourse tasks that rely on input paths.

**Comment by ryanmoran** [comment]
This should be resolved by the PR here: https://github.com/ryanmoran/piper/pull/5
